# Generated by Django 5.2.16 on 2026-08-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_requesttransition_event'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authorityrule',
            name='leave_authority_unique_match',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='leave_request_queue_idx',
        ),
        migrations.RemoveField(
            model_name='authorityrule',
            name='unit_id',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='unit_id',
        ),
        migrations.AddField(
            model_name='authorityrule',
            name='unit',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='unit',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['state', 'unit'], name='leave_request_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='authorityrule',
            constraint=models.UniqueConstraint(fields=('policy_id', 'category', 'unit', 'designation'), name='leave_authority_unique_match'),
        ),
    ]
