# Generated by Django 5.2.16 on 2026-08-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_remove_authorityrule_leave_authority_unique_match_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_id', models.IntegerField(db_index=True)),
                ('state', models.CharField(choices=[('DRAFT', 'DRAFT'), ('AWAITING_SUBSTITUTE', 'AWAITING_SUBSTITUTE'), ('APPLICANT_ACTION_REQUIRED', 'APPLICANT_ACTION_REQUIRED'), ('AWAITING_UNIT_HEAD', 'AWAITING_UNIT_HEAD'), ('AWAITING_ESTABLISHMENT', 'AWAITING_ESTABLISHMENT'), ('AWAITING_FINAL_SANCTION', 'AWAITING_FINAL_SANCTION'), ('AWAITING_SELF_SANCTION', 'AWAITING_SELF_SANCTION'), ('APPROVED_NOT_STARTED', 'APPROVED_NOT_STARTED'), ('ONGOING', 'ONGOING'), ('AWAITING_RESUMPTION', 'AWAITING_RESUMPTION'), ('AWAITING_RESUMPTION_VERIFICATION', 'AWAITING_RESUMPTION_VERIFICATION'), ('CLOSED', 'CLOSED'), ('REJECTED', 'REJECTED'), ('WITHDRAWN', 'WITHDRAWN'), ('CANCELLED', 'CANCELLED'), ('CANCELLATION_UNIT_HEAD', 'CANCELLATION_UNIT_HEAD'), ('CANCELLATION_ESTABLISHMENT', 'CANCELLATION_ESTABLISHMENT'), ('CANCELLATION_FINAL', 'CANCELLATION_FINAL'), ('EXTENSION_AWAITING_SUBSTITUTE', 'EXTENSION_AWAITING_SUBSTITUTE'), ('EXTENSION_APPLICANT_ACTION_REQUIRED', 'EXTENSION_APPLICANT_ACTION_REQUIRED'), ('EXTENSION_AWAITING_UNIT_HEAD', 'EXTENSION_AWAITING_UNIT_HEAD'), ('EXTENSION_AWAITING_ESTABLISHMENT', 'EXTENSION_AWAITING_ESTABLISHMENT'), ('EXTENSION_AWAITING_FINAL', 'EXTENSION_AWAITING_FINAL')], max_length=40)),
                ('remind_after_hours', models.PositiveIntegerField()),
                ('escalate_after_hours', models.PositiveIntegerField()),
                ('escalate_to_designation', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'db_table': 'leave_sla_rule',
                'ordering': ['policy_id', 'state'],
                'constraints': [models.UniqueConstraint(fields=('policy_id', 'state'), name='leave_sla_rule_one_per_state'), models.CheckConstraint(condition=models.Q(('escalate_after_hours__gt', models.F('remind_after_hours'))), name='leave_sla_escalation_after_reminder')],
            },
        ),
    ]
