# Generated by Django 5.2.16 on 2026-08-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_slarule'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='max_backdate_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
