# Generated by Django 5.2.16 on 2026-08-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_leavepolicy_max_backdate_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearEndClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('year', models.IntegerField(db_index=True)),
                ('policy_id', models.IntegerField(blank=True, null=True)),
                ('lapsed', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('carried', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('converted_vl', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('el_from_conversion', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('closed_by_user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leave_year_end_closure',
                'ordering': ['user_id', 'year'],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'year'), name='leave_year_closed_once')],
            },
        ),
    ]
