# Generated by Django 5.2.16 on 2026-08-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_yearendclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='extension_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='extension_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
