# Generated by Django 5.2.16 on 2026-08-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_leaverequest_extension_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='applicant_designation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='authority_rule_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='establishment_step',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='sanctioning_designation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='self_sanction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='unit_head_is_final',
            field=models.BooleanField(default=False),
        ),
    ]
