# Generated by Django 5.2.16 on 2026-08-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_leaverequest_applicant_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='unit_head_recommended',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
