# Generated by Django 5.2.16 on 2026-08-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_leaverequest_unit_head_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='evidence_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
