# Generated by Django 5.2.16 on 2026-08-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_leaverequest_evidence_reference'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('reason', 'ANNUAL_CREDIT')), fields=('user_id', 'year', 'category'), name='leave_ledger_one_annual_credit'),
        ),
    ]
