# Generated by Django 5.2.16 on 2026-08-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRef',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('display_name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('operator', 'Operator')], db_index=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(blank=True, max_length=80)),
                ('programme', models.CharField(blank=True, max_length=40)),
                ('discipline', models.CharField(blank=True, db_index=True, max_length=40)),
                ('batch_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'directory_user_ref',
                'indexes': [models.Index(fields=['kind', 'discipline'], name='userref_kind_disc_idx'), models.Index(fields=['batch_year'], name='userref_batch_idx')],
            },
        ),
    ]
