"""Publish the permission catalogue and its designation grants for the IAM to seed.

    manage.py permission_manifest            write registry/permissions.json
    manage.py permission_manifest --check    fail if stale or ungrantable
"""
import json
from importlib import import_module
from pathlib import Path

from django.apps import apps
from django.conf import settings
from django.core.management.base import BaseCommand, CommandError

MANIFEST = Path(settings.BASE_DIR) / "registry" / "permissions.json"
CATALOGUE = (Path(settings.BASE_DIR) / "docs" / "02-iam"
             / "permission-catalog.generated.md")
VERSION = 1


def collect() -> dict:
    modules = {}
    for cfg in sorted(apps.get_app_configs(), key=lambda c: c.name):
        if not cfg.name.startswith("modules."):
            continue
        try:
            reg = import_module(f"{cfg.name}.registry")
        except ModuleNotFoundError:
            continue
        if not getattr(reg, "PERMISSIONS", None):
            continue
        spec = getattr(reg, "MODULE", None)
        # A module with permissions but no screens still owns its grants.
        code = spec["code"] if spec else cfg.label
        modules[code] = {
            "permissions": [
                {"code": code, "label": label}
                for code, label in getattr(reg, "PERMISSIONS", [])
            ],
            "system_permissions": sorted(getattr(reg, "SYSTEM_PERMISSIONS", [])),
            "grants": {
                designation: sorted(set(codes))
                for designation, codes
                in sorted(getattr(reg, "ROLE_GRANTS", {}).items())
            },
        }
    return {"version": VERSION, "modules": modules}


def problems(manifest: dict) -> list[str]:
    found = []
    for code, spec in manifest["modules"].items():
        declared = {p["code"] for p in spec["permissions"]}
        system = set(spec["system_permissions"])
        granted = {c for codes in spec["grants"].values() for c in codes}

        found.extend(
            f"{code}: {orphan} is declared but no designation holds it, so the "
            f"endpoint guarding on it is unreachable. Grant it in ROLE_GRANTS, "
            f"or list it in SYSTEM_PERMISSIONS if only a service performs it."
            for orphan in sorted(declared - system - granted))
        found.extend(
            f"{code}: {unknown} is granted but not in PERMISSIONS — a typo "
            f"there grants nothing at all."
            for unknown in sorted(granted - declared))
        found.extend(
            f"{code}: {wrong} does not carry the module's prefix, so the IAM "
            f"cannot tell which module owns it."
            for wrong in sorted(c for c in declared
                                if not c.startswith(f"{code}.")))
        found.extend(
            f"{code}: {both} is both a system permission and granted to a "
            f"designation. Pick one."
            for both in sorted(system & granted))
    return found


def render(manifest: dict) -> str:
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def render_catalogue(manifest: dict) -> str:
    lines = [
        "# Permission catalogue (generated)",
        "",
        "Generated by `make permissions` from each module's `registry.py`, and",
        "checked in CI. Every code below is one a view or service actually",
        "guards on, and every designation column is one the IAM can grant.",
        "",
        "For the intended taxonomy of modules not yet built, see",
        "[permission-catalog.md](permission-catalog.md).",
    ]
    for code, spec in sorted(manifest["modules"].items()):
        system = set(spec["system_permissions"])
        holders = {
            p["code"]: sorted(d for d, codes in spec["grants"].items()
                              if p["code"] in codes)
            for p in spec["permissions"]
        }
        lines += ["", f"## `{code}`", "",
                  "| Code | What it allows | Held by |", "|---|---|---|"]
        for p in spec["permissions"]:
            who = ("_service only_" if p["code"] in system
                   else ", ".join(f"`{d}`" for d in holders[p["code"]]))
            lines.append(f"| `{p['code']}` | {p['label']} | {who} |")
    return "\n".join(lines) + "\n"


class Command(BaseCommand):
    help = "Write or verify registry/permissions.json"

    def add_arguments(self, parser):
        parser.add_argument("--check", action="store_true",
                            help="Verify without writing.")

    def handle(self, *args, **opts):
        manifest = collect()
        found = problems(manifest)
        if found:
            raise CommandError("\n".join(["permission manifest is invalid:",
                                          *(f"  - {p}" for p in found)]))

        artifacts = {MANIFEST: render(manifest),
                     CATALOGUE: render_catalogue(manifest)}
        if opts["check"]:
            for path, body in artifacts.items():
                current = path.read_text() if path.exists() else ""
                if current != body:
                    raise CommandError(
                        f"{path.relative_to(settings.BASE_DIR)} is stale — run "
                        f"'make permissions'")
            self.stdout.write("permission manifest matches the registries")
            return

        for path, body in artifacts.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body)
        counts = ", ".join(
            f"{code}: {len(spec['permissions'])} permission(s), "
            f"{len(spec['grants'])} designation(s)"
            for code, spec in manifest["modules"].items())
        self.stdout.write(self.style.SUCCESS(
            f"wrote {MANIFEST.relative_to(settings.BASE_DIR)} — {counts}"))
