# Generated by Django 5.2.16 on 2026-08-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('sector', models.CharField(blank=True, max_length=60)),
                ('tier_rank', models.PositiveSmallIntegerField(blank=True, help_text='1 = best', null=True)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active'), ('blacklisted', 'Blacklisted')], default='prospect', max_length=12)),
            ],
            options={
                'db_table': 'placement_company',
                'indexes': [models.Index(fields=['status', 'name'], name='company_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('placement_year', models.CharField(db_index=True, max_length=12)),
                ('ctc_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('eligibility_rule', models.JSONField(blank=True, default=dict)),
                ('eligibility_rule_locked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Applications closed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user_id', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='placement.company')),
            ],
            options={
                'db_table': 'placement_job_posting',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('offer_issued', 'Offer issued'), ('offer_accepted', 'Offer accepted'), ('offer_declined', 'Offer declined')], default='draft', max_length=20)),
                ('cpi_at_apply', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('eligibility_snapshot', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='placement.jobposting')),
            ],
            options={
                'db_table': 'placement_application',
            },
        ),
        migrations.CreateModel(
            name='ApplicationTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='placement.application')),
            ],
            options={
                'db_table': 'placement_application_transition',
                'indexes': [models.Index(fields=['application', 'at'], name='transition_app_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['placement_year', 'status', 'closes_at'], name='posting_year_status_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['company', 'placement_year'], name='posting_company_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('eligibility_rule_locked_at__isnull', False), _connector='OR'), name='posting_published_has_locked_rule'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.CheckConstraint(condition=models.Q(('closes_at__isnull', True), ('opens_at__isnull', True), ('closes_at__gt', models.F('opens_at')), _connector='OR'), name='posting_window_valid'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['posting', 'status'], name='application_posting_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user_id', 'status'], name='application_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('posting', 'user_id'), name='application_unique_per_posting'),
        ),
    ]
