# Generated by Django 5.2.16 on 2026-08-02 18:23

import django.db.models.deletion
from django.db import migrations, models


def unpublish_incomplete_postings(apps, schema_editor):
    """Make existing rows satisfy PC-BR-003 before the constraint lands.

    A published posting must have a role description and an application
    deadline. Rows predating that rule are moved back to DRAFT rather than
    given placeholder content: inventing a description would leave a posting
    live that nobody wrote, and students would apply against it. Draft is
    recoverable — the office fills in what is missing and publishes again.
    """
    JobPosting = apps.get_model("placement", "JobPosting")
    # `published_at` is added by a later operation in this same migration, so
    # it does not exist in the model state here — and being new, it is NULL for
    # every existing row anyway. Only the status needs correcting.
    JobPosting.objects.filter(status="published").filter(
        models.Q(description="") | models.Q(closes_at__isnull=True)
    ).update(status="draft")


def noop(apps, schema_editor):
    """Reversing cannot know which drafts were previously published, and
    guessing would re-publish something the office had pulled."""


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(unpublish_incomplete_postings, noop),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('topic', models.CharField(choices=[('drive', 'Placement drive'), ('company_visit', 'Company visit'), ('training', 'Training session'), ('workshop', 'Workshop'), ('internship', 'Internship programme'), ('general', 'General')], default='general', max_length=20)),
                ('audience', models.CharField(choices=[('students', 'All students'), ('registered', 'Registered students'), ('alumni', 'Alumni'), ('all', 'Everyone')], default='students', max_length=12)),
                ('placement_year', models.CharField(blank=True, db_index=True, max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by_user_id', models.IntegerField(blank=True, null=True)),
                ('published_by_role', models.CharField(blank=True, max_length=60)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_reason', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'placement_announcement',
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'placement_company_contact',
            },
        ),
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seq', models.PositiveSmallIntegerField(default=1)),
                ('kind', models.CharField(choices=[('test', 'Written / online test'), ('gd', 'Group discussion'), ('tech', 'Technical interview'), ('hr', 'HR interview'), ('other', 'Other')], default='tech', max_length=12)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=8)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('meeting_url', models.URLField(blank=True)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('scheduled_by_user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'placement_interview_round',
            },
        ),
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(db_index=True, max_length=60)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('recipient_user_id', models.IntegerField(blank=True, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'placement_notification_outbox',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('ctc_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tier_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_dream', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked'), ('superseded', 'Superseded'), ('expired', 'Expired')], default='issued', max_length=12)),
                ('respond_by', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('policy_decision', models.JSONField(blank=True, default=dict)),
                ('issued_by_user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'placement_offer',
            },
        ),
        migrations.CreateModel(
            name='PlacementPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.CharField(max_length=12, unique=True)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_offers_allowed', models.PositiveSmallIntegerField(default=1)),
                ('pool_after_offer', models.CharField(choices=[('blocked', 'No further applications once placed'), ('dream_only', 'May apply only above the dream threshold'), ('tier_upgrade_only', 'May apply only to a better tier'), ('unrestricted', 'No restriction')], default='blocked', max_length=20)),
                ('dream_threshold_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('upgrade_tier_rank_delta', models.PositiveSmallIntegerField(default=1)),
                ('min_cpi_to_register', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('allow_backlog_registration', models.BooleanField(default=True)),
                ('default_offer_response_hours', models.PositiveIntegerField(default=72)),
            ],
            options={
                'verbose_name_plural': 'placement policies',
                'db_table': 'placement_policy',
            },
        ),
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('ctc_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('kind', models.CharField(default='fte', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by_user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'placement_record',
            },
        ),
        migrations.CreateModel(
            name='PlacementRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('debarred', 'Debarred'), ('opted_out', 'Opted out')], default='registered', max_length=12)),
                ('offer_count', models.PositiveSmallIntegerField(default=0)),
                ('best_accepted_tier_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('best_accepted_ctc_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('debarred_reason', models.CharField(blank=True, max_length=300)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'placement_registration',
            },
        ),
        migrations.CreateModel(
            name='PlacementStatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.CharField(max_length=32)),
                ('dimension_value', models.CharField(blank=True, max_length=120)),
                ('registered', models.IntegerField(default=0)),
                ('placed', models.IntegerField(default=0)),
                ('offers', models.IntegerField(default=0)),
                ('companies_participated', models.IntegerField(default=0)),
                ('median_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mean_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'placement_stats_snapshot',
            },
        ),
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('kind', models.CharField(choices=[('resume', 'Resume'), ('certificate', 'Certificate'), ('offer_letter', 'Offer letter'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'placement_profile_document',
            },
        ),
        migrations.CreateModel(
            name='RecruiterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('password_hash', models.CharField(blank=True, max_length=256)),
                ('invite_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('invite_expires_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by_user_id', models.IntegerField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'placement_recruiter_account',
            },
        ),
        migrations.CreateModel(
            name='RecruiterLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('outcome', models.CharField(max_length=24)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'placement_recruiter_login_attempt',
            },
        ),
        migrations.CreateModel(
            name='RecruiterSession',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'placement_recruiter_session',
            },
        ),
        migrations.CreateModel(
            name='RoundParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('attended', 'Attended'), ('absent', 'Absent'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'placement_round_participation',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(unique=True)),
                ('headline', models.CharField(blank=True, max_length=160)),
                ('about', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('alternate_email', models.EmailField(blank=True, max_length=254)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('completeness_percent', models.PositiveSmallIntegerField(default=0)),
                ('is_complete', models.BooleanField(db_index=True, default=False)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'placement_student_profile',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='cover_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='semester_at_apply',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='standing_declared_seq_at_apply',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='withdrawn_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='applicationtransition',
            name='actor_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='applicationtransition',
            name='actor_recruiter_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='approval_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='company',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending institute approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='company',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='approved_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='hq_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='bond_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='kind',
            field=models.CharField(choices=[('fte', 'Full time'), ('internship', 'Internship'), ('ppo', 'Pre-placement offer')], default='fte', max_length=12),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='stipend_pm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('auto_withdrawn', 'Withdrawn automatically'), ('offer_issued', 'Offer issued'), ('offer_accepted', 'Offer accepted'), ('offer_declined', 'Offer declined'), ('offer_expired', 'Offer expired')], default='draft', max_length=24),
        ),
        migrations.AlterField(
            model_name='applicationtransition',
            name='from_status',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='applicationtransition',
            name='to_status',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending TPO approval'), ('published', 'Published'), ('closed', 'Applications closed'), ('in_progress', 'Selection in progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['approval_status'], name='company_approval_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approval_status', 'approved'), _negated=True), ('approved_by_user_id__isnull', False), _connector='OR'), name='company_approval_is_attributed'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['-published_at'], name='announcement_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['audience', 'is_withdrawn'], name='announcement_audience_idx'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='placement.company'),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='placement.jobposting'),
        ),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['status', 'created_at'], name='outbox_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['recipient_user_id', '-created_at'], name='outbox_recipient_idx'),
        ),
        migrations.AddField(
            model_name='offer',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='placement.application'),
        ),
        migrations.AddField(
            model_name='offer',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='placement.jobposting'),
        ),
        migrations.AddField(
            model_name='placementrecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='placement.company'),
        ),
        migrations.AddField(
            model_name='placementrecord',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='record', to='placement.offer'),
        ),
        migrations.AddField(
            model_name='placementrecord',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='placement.placementpolicy'),
        ),
        migrations.AddField(
            model_name='placementrecord',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='placement.jobposting'),
        ),
        migrations.AddField(
            model_name='placementregistration',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='placement.placementpolicy'),
        ),
        migrations.AddField(
            model_name='placementstatssnapshot',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='placement.placementpolicy'),
        ),
        migrations.AddField(
            model_name='offer',
            name='letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='placement.profiledocument'),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='placement.profiledocument'),
        ),
        migrations.AddField(
            model_name='recruiteraccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='placement.company'),
        ),
        migrations.AddField(
            model_name='offer',
            name='issued_by_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='placement.recruiteraccount'),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='scheduled_by_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='placement.recruiteraccount'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='created_by_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings_created', to='placement.recruiteraccount'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), models.Q(models.Q(('description', ''), _negated=True), ('closes_at__isnull', False)), _connector='OR'), name='posting_published_has_required_content'),
        ),
        migrations.AddIndex(
            model_name='recruiterloginattempt',
            index=models.Index(fields=['email', '-at'], name='recruiter_attempt_idx'),
        ),
        migrations.AddField(
            model_name='recruitersession',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='placement.recruiteraccount'),
        ),
        migrations.AddField(
            model_name='roundparticipation',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='placement.application'),
        ),
        migrations.AddField(
            model_name='roundparticipation',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='placement.interviewround'),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='placement.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='companycontact',
            index=models.Index(fields=['company', 'is_primary'], name='contact_company_idx'),
        ),
        migrations.AddIndex(
            model_name='placementrecord',
            index=models.Index(fields=['policy', 'company'], name='record_season_idx'),
        ),
        migrations.AddIndex(
            model_name='placementrecord',
            index=models.Index(fields=['user_id', 'is_active'], name='record_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='placementrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user_id', 'policy'), name='one_active_placement_per_student_per_season'),
        ),
        migrations.AddIndex(
            model_name='placementregistration',
            index=models.Index(fields=['policy', 'status'], name='registration_season_idx'),
        ),
        migrations.AddConstraint(
            model_name='placementregistration',
            constraint=models.UniqueConstraint(fields=('policy', 'user_id'), name='registration_unique_per_season'),
        ),
        migrations.AddConstraint(
            model_name='placementstatssnapshot',
            constraint=models.UniqueConstraint(fields=('policy', 'dimension', 'dimension_value'), name='snapshot_unique_dimension'),
        ),
        migrations.AddIndex(
            model_name='recruiteraccount',
            index=models.Index(fields=['company', 'is_active'], name='recruiter_company_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['user_id', 'status'], name='offer_user_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['posting', 'status'], name='offer_posting_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'respond_by'], name='offer_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewround',
            index=models.Index(fields=['posting', 'seq'], name='round_posting_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewround',
            index=models.Index(fields=['starts_at'], name='round_when_idx'),
        ),
        migrations.AddConstraint(
            model_name='interviewround',
            constraint=models.UniqueConstraint(fields=('posting', 'seq'), name='round_unique_seq_per_posting'),
        ),
        migrations.AddConstraint(
            model_name='interviewround',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='round_time_valid'),
        ),
        migrations.AddConstraint(
            model_name='interviewround',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mode', 'online'), models.Q(('meeting_url', ''), _negated=True)), models.Q(('mode', 'offline'), models.Q(('venue', ''), _negated=True)), _connector='OR'), name='round_has_a_location'),
        ),
        migrations.AddIndex(
            model_name='recruitersession',
            index=models.Index(fields=['account', '-created_at'], name='recruiter_session_idx'),
        ),
        migrations.AddIndex(
            model_name='roundparticipation',
            index=models.Index(fields=['round', 'outcome'], name='participation_round_idx'),
        ),
        migrations.AddConstraint(
            model_name='roundparticipation',
            constraint=models.UniqueConstraint(fields=('round', 'application'), name='participation_unique'),
        ),
        migrations.AddIndex(
            model_name='profiledocument',
            index=models.Index(fields=['profile', 'kind', 'is_active'], name='document_profile_idx'),
        ),
    ]
