# Generated by Django 5.2.16 on 2026-08-02 20:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_announcement_companycontact_interviewround_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementpolicy',
            name='dream_threshold_lpa',
        ),
        migrations.RemoveField(
            model_name='placementpolicy',
            name='max_offers_allowed',
        ),
        migrations.RemoveField(
            model_name='placementpolicy',
            name='pool_after_offer',
        ),
        migrations.RemoveField(
            model_name='placementpolicy',
            name='upgrade_tier_rank_delta',
        ),
        migrations.AddField(
            model_name='company',
            name='is_marquee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='sector_kind',
            field=models.CharField(choices=[('it', 'IT / software'), ('core', 'Core engineering'), ('other', 'Other')], default='other', max_length=8),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='dream_slot_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='is_dream_slot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placementpolicy',
            name='discipline_groups',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='placementpolicy',
            name='late_registration_fee',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='placementpolicy',
            name='mandatory_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementpolicy',
            name='reregistration_fee',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='placementregistration',
            name='category_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementregistration',
            name='category_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementregistration',
            name='consent_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='placementregistration',
            name='held_is_marquee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placementregistration',
            name='held_sector_kind',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='placementregistration',
            name='registered_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placementregistration',
            name='reregistration_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='placementregistration',
            name='switches_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('cse_ece', 'CSE & ECE'), ('core', 'ME, SM and Core'), ('design', 'Design')], max_length=12)),
                ('number', models.PositiveSmallIntegerField()),
                ('ctc_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ctc_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('switch_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=4)),
                ('switch_floor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('exit_above', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_switches', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='placement.placementpolicy')),
            ],
            options={
                'verbose_name_plural': 'policy categories',
                'db_table': 'placement_policy_category',
                'ordering': ['group', 'number'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'group', 'number'), name='policy_category_unique'), models.CheckConstraint(condition=models.Q(('ctc_min__isnull', True), ('ctc_max__isnull', True), ('ctc_max__gte', models.F('ctc_min')), _connector='OR'), name='policy_category_band_valid')],
            },
        ),
    ]
