# Generated by Django 5.2.16 on 2026-08-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_remove_placementpolicy_dream_threshold_lpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledocument',
            name='drive_file_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='drive_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profiledocument',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profiledocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profiledocument',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profiledocument',
            name='size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiledocument',
            name='storage_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='profiledocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('drive_file_id', ''), ('storage_key__isnull', False)), models.Q(models.Q(('drive_file_id', ''), _negated=True), ('storage_key__isnull', True)), _connector='OR'), name='document_is_link_or_file_not_both'),
        ),
    ]
