# Generated by Django 5.2.16 on 2026-08-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_document_drive_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationoutbox',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationoutbox',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], default='pending', max_length=12),
        ),
    ]
