# Generated by Django 5.2.16 on 2026-08-03 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_outbox_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementregistration',
            name='sanction',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='placementregistration',
            name='sanction_rule',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='placementregistration',
            name='sanctioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementregistration',
            name='sanctioned_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConductIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('kind', models.CharField(choices=[('consent_failure', 'Did not appear after consenting (r19)'), ('code_of_conduct', 'Code of conduct (r21)'), ('misrepresentation', 'False resume or unfair means (r18)')], max_length=20)),
                ('note', models.CharField(max_length=300)),
                ('recorded_by_user_id', models.IntegerField()),
                ('waived', models.BooleanField(default=False)),
                ('waived_reason', models.CharField(blank=True, max_length=300)),
                ('waived_by_user_id', models.IntegerField(blank=True, null=True)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='placement.jobposting')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='placement.placementregistration')),
            ],
            options={
                'db_table': 'placement_conduct_incident',
                'indexes': [models.Index(fields=['registration', 'kind', 'waived'], name='incident_ladder_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('waived', False), models.Q(('waived', True), models.Q(('waived_reason', ''), _negated=True), ('waived_by_user_id__isnull', False)), _connector='OR'), name='incident_waiver_is_attributed')],
            },
        ),
    ]
