# Generated by Django 5.2.16 on 2026-08-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0006_conduct_incidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementpolicy',
            name='registration_closes_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementregistration',
            name='approved_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementregistration',
            name='late_fee_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='placementregistration',
            name='reregistration_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
