# Generated by Django 5.2.16 on 2026-08-03 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_registration_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementpolicy',
            name='notify_non_joining_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementrecord',
            name='not_joining_declared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementrecord',
            name='not_joining_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='placementrecord',
            name='not_joining_was_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placementrecord',
            name='offer_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_letter_for', to='placement.profiledocument'),
        ),
        migrations.AddField(
            model_name='placementrecord',
            name='offer_letter_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementrecord',
            name='source',
            field=models.CharField(choices=[('campus', 'Through the Placement Cell'), ('off_campus', 'Off campus (rules 5 and 24)')], default='campus', max_length=12),
        ),
        migrations.AlterField(
            model_name='placementrecord',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='record', to='placement.offer'),
        ),
        migrations.AlterField(
            model_name='placementrecord',
            name='posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='placement.jobposting'),
        ),
        migrations.AddConstraint(
            model_name='placementrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('offer__isnull', False), ('posting__isnull', False), ('source', 'campus')), models.Q(('offer__isnull', True), ('posting__isnull', True), ('source', 'off_campus')), _connector='OR'), name='record_source_matches_its_origin'),
        ),
    ]
