# Generated by Django 5.2.16 on 2026-09-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0008_post_offer_obligations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledocument',
            name='profile',
        ),
        migrations.RemoveIndex(
            model_name='profiledocument',
            name='document_profile_idx',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.AlterField(
            model_name='profiledocument',
            name='kind',
            field=models.CharField(choices=[('certificate', 'Certificate'), ('offer_letter', 'Offer letter'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='profiledocument',
            index=models.Index(fields=['user_id', 'kind', 'is_active'], name='document_user_idx'),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
