# Generated by Django 5.2.16 on 2026-08-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('icon', models.CharField(default='FaCircle', max_length=48)),
                ('base_path', models.CharField(max_length=80)),
                ('nav_section', models.CharField(default='Modules', max_length=48)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='planned', max_length=16)),
            ],
            options={
                'db_table': 'accesscontrol_module',
                'ordering': ['nav_section', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('icon', models.CharField(default='FaCircle', max_length=48)),
                ('to', models.CharField(max_length=160)),
                ('required_permission', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='accesscontrol.module')),
            ],
            options={
                'db_table': 'accesscontrol_nav_item',
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
